name = "oas_generator"
version = "1.0.0"
target = "javascript"
description = "Generate HTTP clients from Open API specs."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "oas_generator" }
links = []

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glance = ">= 3.0.0 and < 4.0.0"
glance_printer ={git = "https://github.com/crowdhailer/glance_printer", ref= "44158b3238b8d112e1a1d3b99db9f7f68f2fe511"}
gleam_http = ">= 3.7.2 and < 4.0.0"
justin = ">= 1.0.1 and < 2.0.0"
midas_node = ">= 1.2.5 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
oas = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.7 and < 2.0.0"
